/*
 * APOTEK ANA FARMA — DEV APP SHELL / NAVIGATION V18.8
 *
 * Satu router SPA untuk /dev.
 * Owner  : akses penuh, aksi utama = Kelola Stok.
 * Pegawai: akses operasional, aksi utama = Transaksi.
 * Back/Forward menggunakan History API tanpa meninggalkan SPA.
 */
(function () {
  'use strict';
  const VERSION='2026-08-27-DEV-NAV-18-8',ROLE_OWNER='Owner',ROLE_PEGAWAI='Pegawai',MARK='ana-farma-dev',TOPBAR_ID='dev-app-topbar',MENU_ID='dev-account-menu';
  const NAV={dashboard:{icon:'⌂',label:'Beranda'},kasir:{icon:'🧾',label:'Transaksi'},stok:{icon:'📦',label:'Kelola Stok'},riwayat:{icon:'🕘',label:'Riwayat'},laporan:{icon:'📊',label:'Laporan'},pembelian:{icon:'🚚',label:'Pembelian'},retur:{icon:'↩️',label:'Retur'},opname:{icon:'📋',label:'Opname'},pelanggan:{icon:'👥',label:'Pelanggan'},profil:{icon:'👤',label:'Profil'}};
  const OWNER_SCREENS=['dashboard','kasir','stok','riwayat','pembelian','retur','pelanggan','supplier','laporan','opname','pengajuan','pengaturan','users','profil'];
  const PEGAWAI_SCREENS=['dashboard','kasir','riwayat','pembelian','retur','pelanggan','opname','profil'];
  let originalSetScreen=null,installed=false,historyReady=false,lastUserKey=null;
  function appState(){return window.AppState||null;} function currentUser(){return appState()&&appState().user;} function isOwner(){return String(currentUser()?.role||'').trim().toLowerCase()==='owner';} function allowedScreens(){return isOwner()?OWNER_SCREENS:PEGAWAI_SCREENS;} function validScreen(screen){return allowedScreens().includes(screen)?screen:'dashboard';}
  function esc(value){return typeof window.escapeHtml==='function'?window.escapeHtml(value):String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]||c));}
  function injectStyle(){if(document.getElementById('dev-shell-style'))return;const style=document.createElement('style');style.id='dev-shell-style';style.textContent=`#${TOPBAR_ID}{position:sticky;top:0;z-index:50;display:flex;align-items:center;gap:10px;padding:calc(10px + env(safe-area-inset-top)) 14px 10px;background:rgba(255,255,255,.94);backdrop-filter:blur(14px);border-bottom:1px solid rgba(20,35,38,.06);box-shadow:0 6px 24px rgba(20,35,38,.06)}#${TOPBAR_ID}.hidden{display:none!important}#${TOPBAR_ID} .dev-brand-emblem{width:36px;height:36px;object-fit:contain;flex-shrink:0}#${TOPBAR_ID} .dev-brand-text{flex:1;min-width:0;cursor:pointer}#${TOPBAR_ID} .dev-brand-text b{display:block;font-size:15px;font-weight:850;color:#0b6f68;line-height:1.2;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}#${TOPBAR_ID} .dev-brand-text span{display:block;font-size:11px;color:#68777a;white-space:nowrap;overflow:hidden;text-overflow:ellipsis;margin-top:2px}#${TOPBAR_ID} .dev-top-actions{display:flex;align-items:center;gap:7px}#${TOPBAR_ID} .dev-icon-btn{width:38px;height:38px;border:0;border-radius:50%;background:#eef3f2;display:flex;align-items:center;justify-content:center;font-size:18px;flex-shrink:0}#${TOPBAR_ID} .dev-back{display:none}.dev-back.show{display:flex!important}#${TOPBAR_ID} .dev-role{font-size:10px;font-weight:850;color:#0f8f83}#${MENU_ID}{position:fixed;right:12px;top:calc(62px + env(safe-area-inset-top));z-index:120;width:min(290px,calc(100vw - 24px));padding:8px;background:rgba(255,255,255,.96);backdrop-filter:blur(16px);border:1px solid rgba(20,35,38,.08);border-radius:16px;box-shadow:0 18px 45px rgba(20,35,38,.14);display:none}#${MENU_ID}.show{display:block}#${MENU_ID} .dev-account-head{padding:11px 10px 13px;border-bottom:1px solid #e3e9e8;margin-bottom:6px}#${MENU_ID} .dev-account-name{font-size:14px;font-weight:850}.dev-account-sub{font-size:11px;color:#68777a;margin-top:3px}#${MENU_ID} button{width:100%;display:flex;align-items:center;gap:9px;border:0;background:transparent;text-align:left;padding:11px 10px;border-radius:10px;font-size:13px;font-weight:700}#${MENU_ID} button:hover{background:#f4f8f7}.dev-danger{color:#dc2626!important}@media(min-width:700px){#${TOPBAR_ID}{padding-left:24px;padding-right:24px}#${MENU_ID}{right:24px}}`;document.head.appendChild(style);}
  function ensureChrome(){const app=document.getElementById('app'),screenRoot=document.getElementById('screen-root');if(!app||!screenRoot)return false;let topbar=document.getElementById(TOPBAR_ID);if(!topbar){topbar=document.createElement('header');topbar.id=TOPBAR_ID;topbar.className='hidden';topbar.innerHTML=`<button class="dev-icon-btn dev-back" data-dev-shell="back" title="Kembali" aria-label="Kembali">←</button><img class="dev-brand-emblem" src="icon-192.png" alt="Ana Farma" decoding="async"><div class="dev-brand-text" data-dev-shell="home"><b data-dev-shell="title">APOTEK ANA FARMA</b><span data-dev-shell="user">-</span></div><div class="dev-top-actions"><button class="dev-icon-btn" data-dev-shell="profile" title="Akun" aria-label="Akun">👤</button></div>`;app.insertBefore(topbar,screenRoot);}let menu=document.getElementById(MENU_ID);if(!menu){menu=document.createElement('div');menu.id=MENU_ID;menu.innerHTML=`<div class="dev-account-head"><div class="dev-account-name" data-dev-account="name">-</div><div class="dev-account-sub" data-dev-account="role">-</div></div><button data-dev-menu="profil">👤 Profil</button><button data-dev-menu="pengaturan" data-owner-only="1">⚙️ Pengaturan</button><button data-dev-menu="users" data-owner-only="1">🔐 Manajemen Pengguna</button><button class="dev-danger" data-dev-menu="logout">🚪 Keluar</button>`;document.body.appendChild(menu);}return true;}
  function renderChrome(){const topbar=document.getElementById(TOPBAR_ID),menu=document.getElementById(MENU_ID),u=currentUser(),nav=document.getElementById('bottom-nav');if(!topbar)return;topbar.classList.toggle('hidden',!u);if(!u){menu?.classList.remove('show');nav?.classList.add('hidden');return;}const name=u.nama||u.username||'Pengguna',role=u.role||ROLE_PEGAWAI,online=appState()?.isOnline?'ONLINE':'OFFLINE',userEl=topbar.querySelector('[data-dev-shell="user"]');if(userEl)userEl.innerHTML=`${esc(name)} • <span class="dev-role">${esc(role)} • ${online}</span>`;if(menu){menu.querySelector('[data-dev-account="name"]').textContent=name;menu.querySelector('[data-dev-account="role"]').textContent=`${role} • ${u.username||''}`;menu.querySelectorAll('[data-owner-only="1"]').forEach(el=>el.classList.toggle('hidden',!isOwner()));}if(!nav)return;nav.classList.remove('hidden');const items=isOwner()?['dashboard','stok','kasir','laporan','profil']:['kasir','riwayat','pembelian','retur','opname','pelanggan'],current=validScreen(appState()?.currentScreen||'dashboard');nav.innerHTML=items.map(key=>{const item=NAV[key],label=key==='stok'?'Kelola Stok':item.label;return `<button class="nav-item ${current===key?'active':''}" data-action="navigate" data-screen="${key}" aria-label="${esc(label)}"><span class="nav-icon">${item.icon}</span><span>${esc(label)}</span></button>`;}).join('');const back=topbar.querySelector('[data-dev-shell="back"]');if(back)back.classList.toggle('show',current!=='dashboard');}
  function initHistory(){if(historyReady)return;const initial=validScreen(appState()?.currentScreen||'dashboard'),state=history.state;if(!state||state[MARK]!==true)history.replaceState({...(state||{}),[MARK]:true,screen:initial},'',`#${initial}`);else if(!state.screen)history.replaceState({...state,[MARK]:true,screen:initial},'',`#${initial}`);historyReady=true;}
  function navigate(screen,push){if(!currentUser())return;const target=validScreen(screen);initHistory();const current=validScreen(appState()?.currentScreen||'dashboard');if(push!==false&&current!==target)history.pushState({[MARK]:true,screen:target},'',`#${target}`);if(typeof originalSetScreen==='function')originalSetScreen(target);if(appState())appState().currentScreen=target;renderChrome();}
  function onPopState(event){if(!currentUser())return;const state=event.state;if(state&&state[MARK]===true){navigate(state.screen||'dashboard',false);return;}history.pushState({[MARK]:true,screen:'dashboard'},'','#dashboard');navigate('dashboard',false);}
  function logout(){if(typeof window.logout==='function')window.logout();else{localStorage.removeItem('anafarma_sesi_v2');if(appState()){appState().user=null;appState().cart=[];appState().cartCustomer=null;}if(typeof window.tampilkanLogin==='function')window.tampilkanLogin();else location.reload();}history.replaceState({[MARK]:true,screen:'login'},'','#login');historyReady=false;renderChrome();}
  function installEvents(){document.addEventListener('click',event=>{const target=event.target.closest('[data-action="navigate"],[data-nav]');if(target){event.preventDefault();event.stopImmediatePropagation();navigate(target.dataset.screen||target.dataset.nav,true);return;}const back=event.target.closest('[data-dev-shell="back"]');if(back){event.preventDefault();event.stopImmediatePropagation();if(appState()?.currentScreen&&appState().currentScreen!=='dashboard')history.back();else navigate('dashboard',false);return;}const profile=event.target.closest('[data-dev-shell="profile"]');if(profile){event.preventDefault();event.stopImmediatePropagation();renderChrome();document.getElementById(MENU_ID)?.classList.toggle('show');return;}const home=event.target.closest('[data-dev-shell="home"]');if(home){event.preventDefault();navigate('dashboard',true);return;}const menuItem=event.target.closest('[data-dev-menu]');if(menuItem){event.preventDefault();const action=menuItem.dataset.devMenu;document.getElementById(MENU_ID)?.classList.remove('show');if(action==='logout')logout();else navigate(action,true);return;}const menu=document.getElementById(MENU_ID),profileButton=document.querySelector(`#${TOPBAR_ID} [data-dev-shell="profile"]`);if(menu?.classList.contains('show')&&!menu.contains(event.target)&&!profileButton?.contains(event.target))menu.classList.remove('show');},true);window.addEventListener('popstate',onPopState);window.addEventListener('online',renderChrome);window.addEventListener('offline',renderChrome);}
  function monitorSession(){const check=()=>{const u=currentUser(),key=u?String(u.idUser||u.username||u.nama||'logged'):null;if(key!==lastUserKey){lastUserKey=key;if(u){initHistory();navigate(validScreen(appState()?.currentScreen||'dashboard'),false);}else{historyReady=false;document.getElementById(MENU_ID)?.classList.remove('show');renderChrome();}}};window.setInterval(check,1000);check();}
  function init(){if(installed)return;installed=true;injectStyle();if(!ensureChrome()){installed=false;setTimeout(init,100);return;}originalSetScreen=window.setScreen;if(typeof originalSetScreen==='function')window.setScreen=screen=>navigate(screen,true);installEvents();monitorSession();window.__ANA_FARMA_DEV_NAV_VERSION__=VERSION;console.info('[DEV NAV] installed',VERSION);}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
})();
